name: hive_local_storage_tanjim
description: "hive local storage"
version: 0.0.4
homepage: https://github.com/Lone-wolf-ai/local_storage
repository: https://github.com/Lone-wolf-ai/local_storage

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter:
